# Generated by Django 3.0.8 on 2020-07-09 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subhead', models.CharField(max_length=200)),
                ('fullhead', models.CharField(max_length=400)),
                ('text', models.TextField()),
                ('point', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
