# Generated by Django 3.0.8 on 2020-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
